/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  
export declare namespace GatewaySettingManager {
      
    export type TokenFeeSettingsStruct = {senderToProvider: BigNumberish, providerToAggregator: BigNumberish, senderToAggregator: BigNumberish, providerToAggregatorFx: BigNumberish}

    export type TokenFeeSettingsStructOutput = [senderToProvider: bigint, providerToAggregator: bigint, senderToAggregator: bigint, providerToAggregatorFx: bigint] & {senderToProvider: bigint, providerToAggregator: bigint, senderToAggregator: bigint, providerToAggregatorFx: bigint }
  
    }

  export interface GatewaySettingManagerInterface extends Interface {
    getFunction(nameOrSignature: "acceptOwnership" | "getTokenFeeSettings" | "owner" | "pendingOwner" | "renounceOwnership" | "setTokenFeeSettings" | "settingManagerBool" | "transferOwnership" | "updateProtocolAddress"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "Initialized" | "OwnershipTransferStarted" | "OwnershipTransferred" | "ProtocolAddressUpdated" | "SetFeeRecipient" | "SettingManagerBool" | "TokenFeeSettingsUpdated"): EventFragment;

    encodeFunctionData(functionFragment: 'acceptOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'getTokenFeeSettings', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingOwner', values?: undefined): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setTokenFeeSettings', values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'settingManagerBool', values: [BytesLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'updateProtocolAddress', values: [BytesLike, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'acceptOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokenFeeSettings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTokenFeeSettings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'settingManagerBool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateProtocolAddress', data: BytesLike): Result;
  }

  
    export namespace InitializedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferStartedEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProtocolAddressUpdatedEvent {
      export type InputTuple = [what: BytesLike, treasuryAddress: AddressLike];
      export type OutputTuple = [what: string, treasuryAddress: string];
      export interface OutputObject {what: string, treasuryAddress: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SetFeeRecipientEvent {
      export type InputTuple = [treasuryAddress: AddressLike];
      export type OutputTuple = [treasuryAddress: string];
      export interface OutputObject {treasuryAddress: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SettingManagerBoolEvent {
      export type InputTuple = [what: BytesLike, value: AddressLike, status: BigNumberish];
      export type OutputTuple = [what: string, value: string, status: bigint];
      export interface OutputObject {what: string, value: string, status: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenFeeSettingsUpdatedEvent {
      export type InputTuple = [token: AddressLike, senderToProvider: BigNumberish, providerToAggregator: BigNumberish, senderToAggregator: BigNumberish, providerToAggregatorFx: BigNumberish];
      export type OutputTuple = [token: string, senderToProvider: bigint, providerToAggregator: bigint, senderToAggregator: bigint, providerToAggregatorFx: bigint];
      export interface OutputObject {token: string, senderToProvider: bigint, providerToAggregator: bigint, senderToAggregator: bigint, providerToAggregatorFx: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface GatewaySettingManager extends BaseContract {
    
    connect(runner?: ContractRunner | null): GatewaySettingManager;
    waitForDeployment(): Promise<this>;

    interface: GatewaySettingManagerInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    acceptOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    getTokenFeeSettings: TypedContractMethod<
      [token: AddressLike, ],
      [GatewaySettingManager.TokenFeeSettingsStructOutput],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pendingOwner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setTokenFeeSettings: TypedContractMethod<
      [token: AddressLike, senderToProvider: BigNumberish, providerToAggregator: BigNumberish, senderToAggregator: BigNumberish, providerToAggregatorFx: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    settingManagerBool: TypedContractMethod<
      [what: BytesLike, value: AddressLike, status: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    updateProtocolAddress: TypedContractMethod<
      [what: BytesLike, value: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'acceptOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getTokenFeeSettings'): TypedContractMethod<
      [token: AddressLike, ],
      [GatewaySettingManager.TokenFeeSettingsStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pendingOwner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTokenFeeSettings'): TypedContractMethod<
      [token: AddressLike, senderToProvider: BigNumberish, providerToAggregator: BigNumberish, senderToAggregator: BigNumberish, providerToAggregatorFx: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'settingManagerBool'): TypedContractMethod<
      [what: BytesLike, value: AddressLike, status: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateProtocolAddress'): TypedContractMethod<
      [what: BytesLike, value: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'Initialized'): TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferStarted'): TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'ProtocolAddressUpdated'): TypedContractEvent<ProtocolAddressUpdatedEvent.InputTuple, ProtocolAddressUpdatedEvent.OutputTuple, ProtocolAddressUpdatedEvent.OutputObject>;
getEvent(key: 'SetFeeRecipient'): TypedContractEvent<SetFeeRecipientEvent.InputTuple, SetFeeRecipientEvent.OutputTuple, SetFeeRecipientEvent.OutputObject>;
getEvent(key: 'SettingManagerBool'): TypedContractEvent<SettingManagerBoolEvent.InputTuple, SettingManagerBoolEvent.OutputTuple, SettingManagerBoolEvent.OutputObject>;
getEvent(key: 'TokenFeeSettingsUpdated'): TypedContractEvent<TokenFeeSettingsUpdatedEvent.InputTuple, TokenFeeSettingsUpdatedEvent.OutputTuple, TokenFeeSettingsUpdatedEvent.OutputObject>;

    filters: {
      
      'Initialized(uint8)': TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
      Initialized: TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
    

      'OwnershipTransferStarted(address,address)': TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
      OwnershipTransferStarted: TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'ProtocolAddressUpdated(bytes32,address)': TypedContractEvent<ProtocolAddressUpdatedEvent.InputTuple, ProtocolAddressUpdatedEvent.OutputTuple, ProtocolAddressUpdatedEvent.OutputObject>;
      ProtocolAddressUpdated: TypedContractEvent<ProtocolAddressUpdatedEvent.InputTuple, ProtocolAddressUpdatedEvent.OutputTuple, ProtocolAddressUpdatedEvent.OutputObject>;
    

      'SetFeeRecipient(address)': TypedContractEvent<SetFeeRecipientEvent.InputTuple, SetFeeRecipientEvent.OutputTuple, SetFeeRecipientEvent.OutputObject>;
      SetFeeRecipient: TypedContractEvent<SetFeeRecipientEvent.InputTuple, SetFeeRecipientEvent.OutputTuple, SetFeeRecipientEvent.OutputObject>;
    

      'SettingManagerBool(bytes32,address,uint256)': TypedContractEvent<SettingManagerBoolEvent.InputTuple, SettingManagerBoolEvent.OutputTuple, SettingManagerBoolEvent.OutputObject>;
      SettingManagerBool: TypedContractEvent<SettingManagerBoolEvent.InputTuple, SettingManagerBoolEvent.OutputTuple, SettingManagerBoolEvent.OutputObject>;
    

      'TokenFeeSettingsUpdated(address,uint256,uint256,uint256,uint256)': TypedContractEvent<TokenFeeSettingsUpdatedEvent.InputTuple, TokenFeeSettingsUpdatedEvent.OutputTuple, TokenFeeSettingsUpdatedEvent.OutputObject>;
      TokenFeeSettingsUpdated: TypedContractEvent<TokenFeeSettingsUpdatedEvent.InputTuple, TokenFeeSettingsUpdatedEvent.OutputTuple, TokenFeeSettingsUpdatedEvent.OutputObject>;
    
    };
  }