/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */


import { ethers } from 'ethers'
import { DeployContractOptions, FactoryOptions, HardhatEthersHelpers as HardhatEthersHelpersBase} from "@nomicfoundation/hardhat-ethers/types";

import * as Contracts from "./index.js";

declare module "@nomicfoundation/hardhat-ethers/types" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
  getContractFactory(name: 'Gateway', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.Gateway__factory>
getContractFactory(name: 'GatewaySettingManager', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.GatewaySettingManager__factory>
getContractFactory(name: 'IGateway', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.IGateway__factory>
getContractFactory(name: 'MockUSDT', signerOrOptions?: ethers.Signer | FactoryOptions): Promise<Contracts.MockUSDT__factory>

  getContractAt(name: 'Gateway', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.Gateway>
getContractAt(name: 'GatewaySettingManager', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.GatewaySettingManager>
getContractAt(name: 'IGateway', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.IGateway>
getContractAt(name: 'MockUSDT', address: string | ethers.Addressable, signer?: ethers.Signer): Promise<Contracts.MockUSDT>

  deployContract(name: 'Gateway', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Gateway>
deployContract(name: 'GatewaySettingManager', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GatewaySettingManager>
deployContract(name: 'IGateway', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IGateway>
deployContract(name: 'MockUSDT', signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUSDT>

  deployContract(name: 'Gateway', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.Gateway>
deployContract(name: 'GatewaySettingManager', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.GatewaySettingManager>
deployContract(name: 'IGateway', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.IGateway>
deployContract(name: 'MockUSDT', args: any[], signerOrOptions?: ethers.Signer | DeployContractOptions): Promise<Contracts.MockUSDT>

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string | ethers.Addressable,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
    deployContract(
      name: string,
      args: any[],
      signerOrOptions?: ethers.Signer | DeployContractOptions
    ): Promise<ethers.Contract>;
  }
}
  