/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IGateway } from './IGateway.js';
export type { ProviderBatchCallAndSponsor } from './ProviderBatchCallAndSponsor.js';