/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace IGateway {
      
    export type OrderStruct = {sender: AddressLike, token: AddressLike, senderFeeRecipient: AddressLike, senderFee: BigNumberish, protocolFee: BigNumberish, isFulfilled: boolean, isRefunded: boolean, refundAddress: AddressLike, currentBPS: BigNumberish, amount: BigNumberish}

    export type OrderStructOutput = [sender: string, token: string, senderFeeRecipient: string, senderFee: bigint, protocolFee: bigint, isFulfilled: boolean, isRefunded: boolean, refundAddress: string, currentBPS: bigint, amount: bigint] & {sender: string, token: string, senderFeeRecipient: string, senderFee: bigint, protocolFee: bigint, isFulfilled: boolean, isRefunded: boolean, refundAddress: string, currentBPS: bigint, amount: bigint }
  
    }

export declare namespace GatewaySettingManager {
      
    export type TokenFeeSettingsStruct = {senderToProvider: BigNumberish, providerToAggregator: BigNumberish, senderToAggregator: BigNumberish, providerToAggregatorFx: BigNumberish}

    export type TokenFeeSettingsStructOutput = [senderToProvider: bigint, providerToAggregator: bigint, senderToAggregator: bigint, providerToAggregatorFx: bigint] & {senderToProvider: bigint, providerToAggregator: bigint, senderToAggregator: bigint, providerToAggregatorFx: bigint }
  
    }

  export interface TestGatewayInterface extends Interface {
    getFunction(nameOrSignature: "acceptOwnership" | "createOrder" | "getAggregator" | "getOrderInfo" | "getTokenFeeSettings" | "initialize" | "isTokenSupported" | "owner" | "pause" | "paused" | "pendingOwner" | "refund" | "renounceOwnership" | "setTokenFeeSettings" | "settingManagerBool" | "settleIn" | "settleOut" | "transferOwnership" | "unpause" | "updateProtocolAddress"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FxTransferFeeSplit" | "Initialized" | "LocalTransferFeeSplit" | "OrderCreated" | "OrderRefunded" | "OwnershipTransferStarted" | "OwnershipTransferred" | "Paused" | "ProtocolAddressUpdated" | "SenderFeeTransferred" | "SetFeeRecipient" | "SettingManagerBool" | "SettleIn" | "SettleOut" | "TokenFeeSettingsUpdated" | "Unpaused"): EventFragment;

    encodeFunctionData(functionFragment: 'acceptOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'createOrder', values: [AddressLike, BigNumberish, BigNumberish, AddressLike, BigNumberish, AddressLike, string]): string;
encodeFunctionData(functionFragment: 'getAggregator', values?: undefined): string;
encodeFunctionData(functionFragment: 'getOrderInfo', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'getTokenFeeSettings', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'initialize', values?: undefined): string;
encodeFunctionData(functionFragment: 'isTokenSupported', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'owner', values?: undefined): string;
encodeFunctionData(functionFragment: 'pause', values?: undefined): string;
encodeFunctionData(functionFragment: 'paused', values?: undefined): string;
encodeFunctionData(functionFragment: 'pendingOwner', values?: undefined): string;
encodeFunctionData(functionFragment: 'refund', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'renounceOwnership', values?: undefined): string;
encodeFunctionData(functionFragment: 'setTokenFeeSettings', values: [AddressLike, BigNumberish, BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'settingManagerBool', values: [BytesLike, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'settleIn', values: [BytesLike, AddressLike, BigNumberish, AddressLike, BigNumberish, AddressLike, BigNumberish]): string;
encodeFunctionData(functionFragment: 'settleOut', values: [BytesLike, BytesLike, AddressLike, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'transferOwnership', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'unpause', values?: undefined): string;
encodeFunctionData(functionFragment: 'updateProtocolAddress', values: [BytesLike, AddressLike]): string;

    decodeFunctionResult(functionFragment: 'acceptOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getAggregator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOrderInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getTokenFeeSettings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'initialize', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isTokenSupported', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'paused', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'pendingOwner', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'renounceOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'setTokenFeeSettings', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'settingManagerBool', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'settleIn', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'settleOut', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'unpause', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'updateProtocolAddress', data: BytesLike): Result;
  }

  
    export namespace FxTransferFeeSplitEvent {
      export type InputTuple = [orderId: BytesLike, senderAmount: BigNumberish, aggregatorAmount: BigNumberish];
      export type OutputTuple = [orderId: string, senderAmount: bigint, aggregatorAmount: bigint];
      export interface OutputObject {orderId: string, senderAmount: bigint, aggregatorAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace InitializedEvent {
      export type InputTuple = [version: BigNumberish];
      export type OutputTuple = [version: bigint];
      export interface OutputObject {version: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LocalTransferFeeSplitEvent {
      export type InputTuple = [orderId: BytesLike, senderAmount: BigNumberish, providerAmount: BigNumberish, aggregatorAmount: BigNumberish];
      export type OutputTuple = [orderId: string, senderAmount: bigint, providerAmount: bigint, aggregatorAmount: bigint];
      export interface OutputObject {orderId: string, senderAmount: bigint, providerAmount: bigint, aggregatorAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OrderCreatedEvent {
      export type InputTuple = [sender: AddressLike, token: AddressLike, amount: BigNumberish, protocolFee: BigNumberish, orderId: BytesLike, rate: BigNumberish, messageHash: string];
      export type OutputTuple = [sender: string, token: string, amount: bigint, protocolFee: bigint, orderId: string, rate: bigint, messageHash: string];
      export interface OutputObject {sender: string, token: string, amount: bigint, protocolFee: bigint, orderId: string, rate: bigint, messageHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OrderRefundedEvent {
      export type InputTuple = [fee: BigNumberish, orderId: BytesLike];
      export type OutputTuple = [fee: bigint, orderId: string];
      export interface OutputObject {fee: bigint, orderId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferStartedEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OwnershipTransferredEvent {
      export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
      export type OutputTuple = [previousOwner: string, newOwner: string];
      export interface OutputObject {previousOwner: string, newOwner: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace PausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace ProtocolAddressUpdatedEvent {
      export type InputTuple = [what: BytesLike, treasuryAddress: AddressLike];
      export type OutputTuple = [what: string, treasuryAddress: string];
      export interface OutputObject {what: string, treasuryAddress: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SenderFeeTransferredEvent {
      export type InputTuple = [orderId: BytesLike, sender: AddressLike, amount: BigNumberish];
      export type OutputTuple = [orderId: string, sender: string, amount: bigint];
      export interface OutputObject {orderId: string, sender: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SetFeeRecipientEvent {
      export type InputTuple = [treasuryAddress: AddressLike];
      export type OutputTuple = [treasuryAddress: string];
      export interface OutputObject {treasuryAddress: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SettingManagerBoolEvent {
      export type InputTuple = [what: BytesLike, value: AddressLike, status: BigNumberish];
      export type OutputTuple = [what: string, value: string, status: bigint];
      export interface OutputObject {what: string, value: string, status: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SettleInEvent {
      export type InputTuple = [orderId: BytesLike, amount: BigNumberish, recipient: AddressLike, token: AddressLike, aggregatorFee: BigNumberish, rate: BigNumberish];
      export type OutputTuple = [orderId: string, amount: bigint, recipient: string, token: string, aggregatorFee: bigint, rate: bigint];
      export interface OutputObject {orderId: string, amount: bigint, recipient: string, token: string, aggregatorFee: bigint, rate: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SettleOutEvent {
      export type InputTuple = [splitOrderId: BytesLike, orderId: BytesLike, liquidityProvider: AddressLike, settlePercent: BigNumberish, rebatePercent: BigNumberish];
      export type OutputTuple = [splitOrderId: string, orderId: string, liquidityProvider: string, settlePercent: bigint, rebatePercent: bigint];
      export interface OutputObject {splitOrderId: string, orderId: string, liquidityProvider: string, settlePercent: bigint, rebatePercent: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TokenFeeSettingsUpdatedEvent {
      export type InputTuple = [token: AddressLike, senderToProvider: BigNumberish, providerToAggregator: BigNumberish, senderToAggregator: BigNumberish, providerToAggregatorFx: BigNumberish];
      export type OutputTuple = [token: string, senderToProvider: bigint, providerToAggregator: bigint, senderToAggregator: bigint, providerToAggregatorFx: bigint];
      export interface OutputObject {token: string, senderToProvider: bigint, providerToAggregator: bigint, senderToAggregator: bigint, providerToAggregatorFx: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace UnpausedEvent {
      export type InputTuple = [account: AddressLike];
      export type OutputTuple = [account: string];
      export interface OutputObject {account: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface TestGateway extends BaseContract {
    
    connect(runner?: ContractRunner | null): TestGateway;
    waitForDeployment(): Promise<this>;

    interface: TestGatewayInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    acceptOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    createOrder: TypedContractMethod<
      [_token: AddressLike, _amount: BigNumberish, _rate: BigNumberish, _senderFeeRecipient: AddressLike, _senderFee: BigNumberish, _refundAddress: AddressLike, messageHash: string, ],
      [string],
      'nonpayable'
    >
    

    
    getAggregator: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    getOrderInfo: TypedContractMethod<
      [_orderId: BytesLike, ],
      [IGateway.OrderStructOutput],
      'view'
    >
    

    
    getTokenFeeSettings: TypedContractMethod<
      [token: AddressLike, ],
      [GatewaySettingManager.TokenFeeSettingsStructOutput],
      'view'
    >
    

    
    initialize: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    isTokenSupported: TypedContractMethod<
      [_token: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    owner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    pause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    paused: TypedContractMethod<
      [],
      [boolean],
      'view'
    >
    

    
    pendingOwner: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    refund: TypedContractMethod<
      [_fee: BigNumberish, _orderId: BytesLike, ],
      [boolean],
      'nonpayable'
    >
    

    
    renounceOwnership: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    setTokenFeeSettings: TypedContractMethod<
      [token: AddressLike, senderToProvider: BigNumberish, providerToAggregator: BigNumberish, senderToAggregator: BigNumberish, providerToAggregatorFx: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    settingManagerBool: TypedContractMethod<
      [what: BytesLike, value: AddressLike, status: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    settleIn: TypedContractMethod<
      [_orderId: BytesLike, _token: AddressLike, _amount: BigNumberish, _senderFeeRecipient: AddressLike, _senderFee: BigNumberish, _recipient: AddressLike, _rate: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    settleOut: TypedContractMethod<
      [_splitOrderId: BytesLike, _orderId: BytesLike, _liquidityProvider: AddressLike, _settlePercent: BigNumberish, _rebatePercent: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    

    
    transferOwnership: TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >
    

    
    unpause: TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >
    

    
    updateProtocolAddress: TypedContractMethod<
      [what: BytesLike, value: AddressLike, ],
      [void],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'acceptOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createOrder'): TypedContractMethod<
      [_token: AddressLike, _amount: BigNumberish, _rate: BigNumberish, _senderFeeRecipient: AddressLike, _senderFee: BigNumberish, _refundAddress: AddressLike, messageHash: string, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getAggregator'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'getOrderInfo'): TypedContractMethod<
      [_orderId: BytesLike, ],
      [IGateway.OrderStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'getTokenFeeSettings'): TypedContractMethod<
      [token: AddressLike, ],
      [GatewaySettingManager.TokenFeeSettingsStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'initialize'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'isTokenSupported'): TypedContractMethod<
      [_token: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'owner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'pause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'paused'): TypedContractMethod<
      [],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'pendingOwner'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'refund'): TypedContractMethod<
      [_fee: BigNumberish, _orderId: BytesLike, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'renounceOwnership'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'setTokenFeeSettings'): TypedContractMethod<
      [token: AddressLike, senderToProvider: BigNumberish, providerToAggregator: BigNumberish, senderToAggregator: BigNumberish, providerToAggregatorFx: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'settingManagerBool'): TypedContractMethod<
      [what: BytesLike, value: AddressLike, status: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'settleIn'): TypedContractMethod<
      [_orderId: BytesLike, _token: AddressLike, _amount: BigNumberish, _senderFeeRecipient: AddressLike, _senderFee: BigNumberish, _recipient: AddressLike, _rate: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'settleOut'): TypedContractMethod<
      [_splitOrderId: BytesLike, _orderId: BytesLike, _liquidityProvider: AddressLike, _settlePercent: BigNumberish, _rebatePercent: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'transferOwnership'): TypedContractMethod<
      [newOwner: AddressLike, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'unpause'): TypedContractMethod<
      [],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'updateProtocolAddress'): TypedContractMethod<
      [what: BytesLike, value: AddressLike, ],
      [void],
      'nonpayable'
    >;

    getEvent(key: 'FxTransferFeeSplit'): TypedContractEvent<FxTransferFeeSplitEvent.InputTuple, FxTransferFeeSplitEvent.OutputTuple, FxTransferFeeSplitEvent.OutputObject>;
getEvent(key: 'Initialized'): TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
getEvent(key: 'LocalTransferFeeSplit'): TypedContractEvent<LocalTransferFeeSplitEvent.InputTuple, LocalTransferFeeSplitEvent.OutputTuple, LocalTransferFeeSplitEvent.OutputObject>;
getEvent(key: 'OrderCreated'): TypedContractEvent<OrderCreatedEvent.InputTuple, OrderCreatedEvent.OutputTuple, OrderCreatedEvent.OutputObject>;
getEvent(key: 'OrderRefunded'): TypedContractEvent<OrderRefundedEvent.InputTuple, OrderRefundedEvent.OutputTuple, OrderRefundedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferStarted'): TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
getEvent(key: 'OwnershipTransferred'): TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
getEvent(key: 'Paused'): TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
getEvent(key: 'ProtocolAddressUpdated'): TypedContractEvent<ProtocolAddressUpdatedEvent.InputTuple, ProtocolAddressUpdatedEvent.OutputTuple, ProtocolAddressUpdatedEvent.OutputObject>;
getEvent(key: 'SenderFeeTransferred'): TypedContractEvent<SenderFeeTransferredEvent.InputTuple, SenderFeeTransferredEvent.OutputTuple, SenderFeeTransferredEvent.OutputObject>;
getEvent(key: 'SetFeeRecipient'): TypedContractEvent<SetFeeRecipientEvent.InputTuple, SetFeeRecipientEvent.OutputTuple, SetFeeRecipientEvent.OutputObject>;
getEvent(key: 'SettingManagerBool'): TypedContractEvent<SettingManagerBoolEvent.InputTuple, SettingManagerBoolEvent.OutputTuple, SettingManagerBoolEvent.OutputObject>;
getEvent(key: 'SettleIn'): TypedContractEvent<SettleInEvent.InputTuple, SettleInEvent.OutputTuple, SettleInEvent.OutputObject>;
getEvent(key: 'SettleOut'): TypedContractEvent<SettleOutEvent.InputTuple, SettleOutEvent.OutputTuple, SettleOutEvent.OutputObject>;
getEvent(key: 'TokenFeeSettingsUpdated'): TypedContractEvent<TokenFeeSettingsUpdatedEvent.InputTuple, TokenFeeSettingsUpdatedEvent.OutputTuple, TokenFeeSettingsUpdatedEvent.OutputObject>;
getEvent(key: 'Unpaused'): TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;

    filters: {
      
      'FxTransferFeeSplit(bytes32,uint256,uint256)': TypedContractEvent<FxTransferFeeSplitEvent.InputTuple, FxTransferFeeSplitEvent.OutputTuple, FxTransferFeeSplitEvent.OutputObject>;
      FxTransferFeeSplit: TypedContractEvent<FxTransferFeeSplitEvent.InputTuple, FxTransferFeeSplitEvent.OutputTuple, FxTransferFeeSplitEvent.OutputObject>;
    

      'Initialized(uint8)': TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
      Initialized: TypedContractEvent<InitializedEvent.InputTuple, InitializedEvent.OutputTuple, InitializedEvent.OutputObject>;
    

      'LocalTransferFeeSplit(bytes32,uint256,uint256,uint256)': TypedContractEvent<LocalTransferFeeSplitEvent.InputTuple, LocalTransferFeeSplitEvent.OutputTuple, LocalTransferFeeSplitEvent.OutputObject>;
      LocalTransferFeeSplit: TypedContractEvent<LocalTransferFeeSplitEvent.InputTuple, LocalTransferFeeSplitEvent.OutputTuple, LocalTransferFeeSplitEvent.OutputObject>;
    

      'OrderCreated(address,address,uint256,uint256,bytes32,uint256,string)': TypedContractEvent<OrderCreatedEvent.InputTuple, OrderCreatedEvent.OutputTuple, OrderCreatedEvent.OutputObject>;
      OrderCreated: TypedContractEvent<OrderCreatedEvent.InputTuple, OrderCreatedEvent.OutputTuple, OrderCreatedEvent.OutputObject>;
    

      'OrderRefunded(uint256,bytes32)': TypedContractEvent<OrderRefundedEvent.InputTuple, OrderRefundedEvent.OutputTuple, OrderRefundedEvent.OutputObject>;
      OrderRefunded: TypedContractEvent<OrderRefundedEvent.InputTuple, OrderRefundedEvent.OutputTuple, OrderRefundedEvent.OutputObject>;
    

      'OwnershipTransferStarted(address,address)': TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
      OwnershipTransferStarted: TypedContractEvent<OwnershipTransferStartedEvent.InputTuple, OwnershipTransferStartedEvent.OutputTuple, OwnershipTransferStartedEvent.OutputObject>;
    

      'OwnershipTransferred(address,address)': TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
      OwnershipTransferred: TypedContractEvent<OwnershipTransferredEvent.InputTuple, OwnershipTransferredEvent.OutputTuple, OwnershipTransferredEvent.OutputObject>;
    

      'Paused(address)': TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
      Paused: TypedContractEvent<PausedEvent.InputTuple, PausedEvent.OutputTuple, PausedEvent.OutputObject>;
    

      'ProtocolAddressUpdated(bytes32,address)': TypedContractEvent<ProtocolAddressUpdatedEvent.InputTuple, ProtocolAddressUpdatedEvent.OutputTuple, ProtocolAddressUpdatedEvent.OutputObject>;
      ProtocolAddressUpdated: TypedContractEvent<ProtocolAddressUpdatedEvent.InputTuple, ProtocolAddressUpdatedEvent.OutputTuple, ProtocolAddressUpdatedEvent.OutputObject>;
    

      'SenderFeeTransferred(bytes32,address,uint256)': TypedContractEvent<SenderFeeTransferredEvent.InputTuple, SenderFeeTransferredEvent.OutputTuple, SenderFeeTransferredEvent.OutputObject>;
      SenderFeeTransferred: TypedContractEvent<SenderFeeTransferredEvent.InputTuple, SenderFeeTransferredEvent.OutputTuple, SenderFeeTransferredEvent.OutputObject>;
    

      'SetFeeRecipient(address)': TypedContractEvent<SetFeeRecipientEvent.InputTuple, SetFeeRecipientEvent.OutputTuple, SetFeeRecipientEvent.OutputObject>;
      SetFeeRecipient: TypedContractEvent<SetFeeRecipientEvent.InputTuple, SetFeeRecipientEvent.OutputTuple, SetFeeRecipientEvent.OutputObject>;
    

      'SettingManagerBool(bytes32,address,uint256)': TypedContractEvent<SettingManagerBoolEvent.InputTuple, SettingManagerBoolEvent.OutputTuple, SettingManagerBoolEvent.OutputObject>;
      SettingManagerBool: TypedContractEvent<SettingManagerBoolEvent.InputTuple, SettingManagerBoolEvent.OutputTuple, SettingManagerBoolEvent.OutputObject>;
    

      'SettleIn(bytes32,uint256,address,address,uint256,uint96)': TypedContractEvent<SettleInEvent.InputTuple, SettleInEvent.OutputTuple, SettleInEvent.OutputObject>;
      SettleIn: TypedContractEvent<SettleInEvent.InputTuple, SettleInEvent.OutputTuple, SettleInEvent.OutputObject>;
    

      'SettleOut(bytes32,bytes32,address,uint64,uint64)': TypedContractEvent<SettleOutEvent.InputTuple, SettleOutEvent.OutputTuple, SettleOutEvent.OutputObject>;
      SettleOut: TypedContractEvent<SettleOutEvent.InputTuple, SettleOutEvent.OutputTuple, SettleOutEvent.OutputObject>;
    

      'TokenFeeSettingsUpdated(address,uint256,uint256,uint256,uint256)': TypedContractEvent<TokenFeeSettingsUpdatedEvent.InputTuple, TokenFeeSettingsUpdatedEvent.OutputTuple, TokenFeeSettingsUpdatedEvent.OutputObject>;
      TokenFeeSettingsUpdated: TypedContractEvent<TokenFeeSettingsUpdatedEvent.InputTuple, TokenFeeSettingsUpdatedEvent.OutputTuple, TokenFeeSettingsUpdatedEvent.OutputObject>;
    

      'Unpaused(address)': TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
      Unpaused: TypedContractEvent<UnpausedEvent.InputTuple, UnpausedEvent.OutputTuple, UnpausedEvent.OutputObject>;
    
    };
  }