/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../../common.js"
  
export declare namespace IGateway {
      
    export type OrderStruct = {sender: AddressLike, token: AddressLike, senderFeeRecipient: AddressLike, senderFee: BigNumberish, protocolFee: BigNumberish, isFulfilled: boolean, isRefunded: boolean, refundAddress: AddressLike, currentBPS: BigNumberish, amount: BigNumberish}

    export type OrderStructOutput = [sender: string, token: string, senderFeeRecipient: string, senderFee: bigint, protocolFee: bigint, isFulfilled: boolean, isRefunded: boolean, refundAddress: string, currentBPS: bigint, amount: bigint] & {sender: string, token: string, senderFeeRecipient: string, senderFee: bigint, protocolFee: bigint, isFulfilled: boolean, isRefunded: boolean, refundAddress: string, currentBPS: bigint, amount: bigint }
  
    }

  export interface IGatewayInterface extends Interface {
    getFunction(nameOrSignature: "createOrder" | "getOrderInfo" | "isTokenSupported" | "refund" | "settle"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "FxTransferFeeSplit" | "LocalTransferFeeSplit" | "OrderCreated" | "OrderRefunded" | "OrderSettled" | "SenderFeeTransferred"): EventFragment;

    encodeFunctionData(functionFragment: 'createOrder', values: [AddressLike, BigNumberish, BigNumberish, AddressLike, BigNumberish, AddressLike, string]): string;
encodeFunctionData(functionFragment: 'getOrderInfo', values: [BytesLike]): string;
encodeFunctionData(functionFragment: 'isTokenSupported', values: [AddressLike]): string;
encodeFunctionData(functionFragment: 'refund', values: [BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'settle', values: [BytesLike, BytesLike, AddressLike, BigNumberish, BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'createOrder', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getOrderInfo', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'isTokenSupported', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'refund', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'settle', data: BytesLike): Result;
  }

  
    export namespace FxTransferFeeSplitEvent {
      export type InputTuple = [orderId: BytesLike, senderAmount: BigNumberish, aggregatorAmount: BigNumberish];
      export type OutputTuple = [orderId: string, senderAmount: bigint, aggregatorAmount: bigint];
      export interface OutputObject {orderId: string, senderAmount: bigint, aggregatorAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace LocalTransferFeeSplitEvent {
      export type InputTuple = [orderId: BytesLike, senderAmount: BigNumberish, providerAmount: BigNumberish, aggregatorAmount: BigNumberish];
      export type OutputTuple = [orderId: string, senderAmount: bigint, providerAmount: bigint, aggregatorAmount: bigint];
      export interface OutputObject {orderId: string, senderAmount: bigint, providerAmount: bigint, aggregatorAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OrderCreatedEvent {
      export type InputTuple = [sender: AddressLike, token: AddressLike, amount: BigNumberish, protocolFee: BigNumberish, orderId: BytesLike, rate: BigNumberish, messageHash: string];
      export type OutputTuple = [sender: string, token: string, amount: bigint, protocolFee: bigint, orderId: string, rate: bigint, messageHash: string];
      export interface OutputObject {sender: string, token: string, amount: bigint, protocolFee: bigint, orderId: string, rate: bigint, messageHash: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OrderRefundedEvent {
      export type InputTuple = [fee: BigNumberish, orderId: BytesLike];
      export type OutputTuple = [fee: bigint, orderId: string];
      export interface OutputObject {fee: bigint, orderId: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace OrderSettledEvent {
      export type InputTuple = [splitOrderId: BytesLike, orderId: BytesLike, liquidityProvider: AddressLike, settlePercent: BigNumberish, rebatePercent: BigNumberish];
      export type OutputTuple = [splitOrderId: string, orderId: string, liquidityProvider: string, settlePercent: bigint, rebatePercent: bigint];
      export interface OutputObject {splitOrderId: string, orderId: string, liquidityProvider: string, settlePercent: bigint, rebatePercent: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace SenderFeeTransferredEvent {
      export type InputTuple = [sender: AddressLike, amount: BigNumberish];
      export type OutputTuple = [sender: string, amount: bigint];
      export interface OutputObject {sender: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface IGateway extends BaseContract {
    
    connect(runner?: ContractRunner | null): IGateway;
    waitForDeployment(): Promise<this>;

    interface: IGatewayInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    createOrder: TypedContractMethod<
      [_token: AddressLike, _amount: BigNumberish, _rate: BigNumberish, _senderFeeRecipient: AddressLike, _senderFee: BigNumberish, _refundAddress: AddressLike, messageHash: string, ],
      [string],
      'nonpayable'
    >
    

    
    getOrderInfo: TypedContractMethod<
      [_orderId: BytesLike, ],
      [IGateway.OrderStructOutput],
      'view'
    >
    

    
    isTokenSupported: TypedContractMethod<
      [_token: AddressLike, ],
      [boolean],
      'view'
    >
    

    
    refund: TypedContractMethod<
      [_fee: BigNumberish, _orderId: BytesLike, ],
      [boolean],
      'nonpayable'
    >
    

    
    settle: TypedContractMethod<
      [_splitOrderId: BytesLike, _orderId: BytesLike, _liquidityProvider: AddressLike, _settlePercent: BigNumberish, _rebatePercent: BigNumberish, ],
      [boolean],
      'nonpayable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'createOrder'): TypedContractMethod<
      [_token: AddressLike, _amount: BigNumberish, _rate: BigNumberish, _senderFeeRecipient: AddressLike, _senderFee: BigNumberish, _refundAddress: AddressLike, messageHash: string, ],
      [string],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'getOrderInfo'): TypedContractMethod<
      [_orderId: BytesLike, ],
      [IGateway.OrderStructOutput],
      'view'
    >;
getFunction(nameOrSignature: 'isTokenSupported'): TypedContractMethod<
      [_token: AddressLike, ],
      [boolean],
      'view'
    >;
getFunction(nameOrSignature: 'refund'): TypedContractMethod<
      [_fee: BigNumberish, _orderId: BytesLike, ],
      [boolean],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'settle'): TypedContractMethod<
      [_splitOrderId: BytesLike, _orderId: BytesLike, _liquidityProvider: AddressLike, _settlePercent: BigNumberish, _rebatePercent: BigNumberish, ],
      [boolean],
      'nonpayable'
    >;

    getEvent(key: 'FxTransferFeeSplit'): TypedContractEvent<FxTransferFeeSplitEvent.InputTuple, FxTransferFeeSplitEvent.OutputTuple, FxTransferFeeSplitEvent.OutputObject>;
getEvent(key: 'LocalTransferFeeSplit'): TypedContractEvent<LocalTransferFeeSplitEvent.InputTuple, LocalTransferFeeSplitEvent.OutputTuple, LocalTransferFeeSplitEvent.OutputObject>;
getEvent(key: 'OrderCreated'): TypedContractEvent<OrderCreatedEvent.InputTuple, OrderCreatedEvent.OutputTuple, OrderCreatedEvent.OutputObject>;
getEvent(key: 'OrderRefunded'): TypedContractEvent<OrderRefundedEvent.InputTuple, OrderRefundedEvent.OutputTuple, OrderRefundedEvent.OutputObject>;
getEvent(key: 'OrderSettled'): TypedContractEvent<OrderSettledEvent.InputTuple, OrderSettledEvent.OutputTuple, OrderSettledEvent.OutputObject>;
getEvent(key: 'SenderFeeTransferred'): TypedContractEvent<SenderFeeTransferredEvent.InputTuple, SenderFeeTransferredEvent.OutputTuple, SenderFeeTransferredEvent.OutputObject>;

    filters: {
      
      'FxTransferFeeSplit(bytes32,uint256,uint256)': TypedContractEvent<FxTransferFeeSplitEvent.InputTuple, FxTransferFeeSplitEvent.OutputTuple, FxTransferFeeSplitEvent.OutputObject>;
      FxTransferFeeSplit: TypedContractEvent<FxTransferFeeSplitEvent.InputTuple, FxTransferFeeSplitEvent.OutputTuple, FxTransferFeeSplitEvent.OutputObject>;
    

      'LocalTransferFeeSplit(bytes32,uint256,uint256,uint256)': TypedContractEvent<LocalTransferFeeSplitEvent.InputTuple, LocalTransferFeeSplitEvent.OutputTuple, LocalTransferFeeSplitEvent.OutputObject>;
      LocalTransferFeeSplit: TypedContractEvent<LocalTransferFeeSplitEvent.InputTuple, LocalTransferFeeSplitEvent.OutputTuple, LocalTransferFeeSplitEvent.OutputObject>;
    

      'OrderCreated(address,address,uint256,uint256,bytes32,uint256,string)': TypedContractEvent<OrderCreatedEvent.InputTuple, OrderCreatedEvent.OutputTuple, OrderCreatedEvent.OutputObject>;
      OrderCreated: TypedContractEvent<OrderCreatedEvent.InputTuple, OrderCreatedEvent.OutputTuple, OrderCreatedEvent.OutputObject>;
    

      'OrderRefunded(uint256,bytes32)': TypedContractEvent<OrderRefundedEvent.InputTuple, OrderRefundedEvent.OutputTuple, OrderRefundedEvent.OutputObject>;
      OrderRefunded: TypedContractEvent<OrderRefundedEvent.InputTuple, OrderRefundedEvent.OutputTuple, OrderRefundedEvent.OutputObject>;
    

      'OrderSettled(bytes32,bytes32,address,uint64,uint64)': TypedContractEvent<OrderSettledEvent.InputTuple, OrderSettledEvent.OutputTuple, OrderSettledEvent.OutputObject>;
      OrderSettled: TypedContractEvent<OrderSettledEvent.InputTuple, OrderSettledEvent.OutputTuple, OrderSettledEvent.OutputObject>;
    

      'SenderFeeTransferred(address,uint256)': TypedContractEvent<SenderFeeTransferredEvent.InputTuple, SenderFeeTransferredEvent.OutputTuple, SenderFeeTransferredEvent.OutputObject>;
      SenderFeeTransferred: TypedContractEvent<SenderFeeTransferredEvent.InputTuple, SenderFeeTransferredEvent.OutputTuple, SenderFeeTransferredEvent.OutputObject>;
    
    };
  }