/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

  import { Contract, Interface, type ContractRunner } from "ethers";
  import type { IGateway, IGatewayInterface } from "../../ProviderBatchCallAndSponsor.sol/IGateway.js";

  const _abi = [
  {
    "inputs": [],
    "name": "getAggregator",
    "outputs": [
      {
        "internalType": "address",
        "name": "",
        "type": "address"
      }
    ],
    "stateMutability": "view",
    "type": "function"
  }
] as const;

  export class IGateway__factory {
    static readonly abi = _abi;
    static createInterface(): IGatewayInterface {
      return new Interface(_abi) as IGatewayInterface;
    }
    static connect(address: string, runner?: ContractRunner | null): IGateway {
      return new Contract(address, _abi, runner) as unknown as IGateway;
    }
  }
  