/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "../common.js"
  
export declare namespace ProviderBatchCallAndSponsor {
      
    export type CallStruct = {to: AddressLike, value: BigNumberish, data: BytesLike}

    export type CallStructOutput = [to: string, value: bigint, data: string] & {to: string, value: bigint, data: string }
  
    }

  export interface ProviderBatchCallAndSponsorInterface extends Interface {
    getFunction(nameOrSignature: "digestForCurrentNonce" | "domainSeparator" | "execute" | "hashTypedBatch" | "nonce"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "BatchExecuted" | "CallExecuted"): EventFragment;

    encodeFunctionData(functionFragment: 'digestForCurrentNonce', values: [ProviderBatchCallAndSponsor.CallStruct[], BigNumberish]): string;
encodeFunctionData(functionFragment: 'domainSeparator', values?: undefined): string;
encodeFunctionData(functionFragment: 'execute', values: [ProviderBatchCallAndSponsor.CallStruct[], BigNumberish, BytesLike]): string;
encodeFunctionData(functionFragment: 'hashTypedBatch', values: [ProviderBatchCallAndSponsor.CallStruct[], BigNumberish]): string;
encodeFunctionData(functionFragment: 'nonce', values?: undefined): string;

    decodeFunctionResult(functionFragment: 'digestForCurrentNonce', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'domainSeparator', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'execute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'hashTypedBatch', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'nonce', data: BytesLike): Result;
  }

  
    export namespace BatchExecutedEvent {
      export type InputTuple = [nonce: BigNumberish, calls: ProviderBatchCallAndSponsor.CallStruct[]];
      export type OutputTuple = [nonce: bigint, calls: ProviderBatchCallAndSponsor.CallStructOutput[]];
      export interface OutputObject {nonce: bigint, calls: ProviderBatchCallAndSponsor.CallStructOutput[] };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace CallExecutedEvent {
      export type InputTuple = [sender: AddressLike, to: AddressLike, value: BigNumberish, data: BytesLike];
      export type OutputTuple = [sender: string, to: string, value: bigint, data: string];
      export interface OutputObject {sender: string, to: string, value: bigint, data: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface ProviderBatchCallAndSponsor extends BaseContract {
    
    connect(runner?: ContractRunner | null): ProviderBatchCallAndSponsor;
    waitForDeployment(): Promise<this>;

    interface: ProviderBatchCallAndSponsorInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    digestForCurrentNonce: TypedContractMethod<
      [calls: ProviderBatchCallAndSponsor.CallStruct[], deadline: BigNumberish, ],
      [string],
      'view'
    >
    

    
    domainSeparator: TypedContractMethod<
      [],
      [string],
      'view'
    >
    

    
    execute: TypedContractMethod<
      [calls: ProviderBatchCallAndSponsor.CallStruct[], deadline: BigNumberish, signature: BytesLike, ],
      [void],
      'payable'
    >
    

    
    hashTypedBatch: TypedContractMethod<
      [calls: ProviderBatchCallAndSponsor.CallStruct[], deadline: BigNumberish, ],
      [string],
      'view'
    >
    

    
    nonce: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'digestForCurrentNonce'): TypedContractMethod<
      [calls: ProviderBatchCallAndSponsor.CallStruct[], deadline: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'domainSeparator'): TypedContractMethod<
      [],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'execute'): TypedContractMethod<
      [calls: ProviderBatchCallAndSponsor.CallStruct[], deadline: BigNumberish, signature: BytesLike, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'hashTypedBatch'): TypedContractMethod<
      [calls: ProviderBatchCallAndSponsor.CallStruct[], deadline: BigNumberish, ],
      [string],
      'view'
    >;
getFunction(nameOrSignature: 'nonce'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;

    getEvent(key: 'BatchExecuted'): TypedContractEvent<BatchExecutedEvent.InputTuple, BatchExecutedEvent.OutputTuple, BatchExecutedEvent.OutputObject>;
getEvent(key: 'CallExecuted'): TypedContractEvent<CallExecutedEvent.InputTuple, CallExecutedEvent.OutputTuple, CallExecutedEvent.OutputObject>;

    filters: {
      
      'BatchExecuted(uint256,tuple[])': TypedContractEvent<BatchExecutedEvent.InputTuple, BatchExecutedEvent.OutputTuple, BatchExecutedEvent.OutputObject>;
      BatchExecuted: TypedContractEvent<BatchExecutedEvent.InputTuple, BatchExecutedEvent.OutputTuple, BatchExecutedEvent.OutputObject>;
    

      'CallExecuted(address,address,uint256,bytes)': TypedContractEvent<CallExecutedEvent.InputTuple, CallExecutedEvent.OutputTuple, CallExecutedEvent.OutputObject>;
      CallExecuted: TypedContractEvent<CallExecutedEvent.InputTuple, CallExecutedEvent.OutputTuple, CallExecutedEvent.OutputObject>;
    
    };
  }